"""add_maintenance_expense_contract_audit

Revision ID: 1d225b3fd12b
Revises: 7cddff1407cc
Create Date: 2026-02-23 14:32:27.736333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1d225b3fd12b'
down_revision: Union[str, None] = '7cddff1407cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.Enum('CREATE', 'UPDATE', 'DELETE', 'LOGIN', 'LOGOUT', 'EXPORT', name='audit_action'), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('changes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_table('contracts',
    sa.Column('vehicle_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('LEASING', 'RENTAL', 'INSURANCE_CASCO', 'INSURANCE_OSAGO', 'WARRANTY', 'SERVICE_CONTRACT', name='contract_type'), nullable=False),
    sa.Column('contractor', sa.String(length=300), nullable=False),
    sa.Column('contract_number', sa.String(length=100), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('payment_frequency', sa.Enum('ONE_TIME', 'MONTHLY', 'QUARTERLY', 'ANNUAL', name='payment_frequency'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'EXPIRED', 'CANCELLED', 'PENDING_RENEWAL', name='contract_status'), nullable=False),
    sa.Column('auto_renew', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contracts_end_date'), 'contracts', ['end_date'], unique=False)
    op.create_index(op.f('ix_contracts_vehicle_id'), 'contracts', ['vehicle_id'], unique=False)
    op.create_table('expenses',
    sa.Column('vehicle_id', sa.UUID(), nullable=False),
    sa.Column('driver_id', sa.UUID(), nullable=True),
    sa.Column('category', sa.Enum('FUEL', 'PARTS', 'SERVICE', 'INSURANCE', 'TAX', 'FINE', 'PARKING', 'TOLL', 'WASHING', 'OTHER', name='expense_category'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.Enum('KZT', 'RUB', 'USD', 'TRY', name='currency'), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('vendor', sa.String(length=300), nullable=True),
    sa.Column('fuel_liters', sa.Float(), nullable=True),
    sa.Column('fuel_price_per_liter', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('fuel_type', sa.String(length=20), nullable=True),
    sa.Column('mileage_at_refuel', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expenses_date'), 'expenses', ['date'], unique=False)
    op.create_index(op.f('ix_expenses_vehicle_id'), 'expenses', ['vehicle_id'], unique=False)
    op.create_table('maintenance_records',
    sa.Column('vehicle_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('SCHEDULED_SERVICE', 'REPAIR', 'INSPECTION', 'TIRE_CHANGE', 'BODY_REPAIR', 'RECALL', name='maintenance_type'), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('SCHEDULED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='maintenance_status'), nullable=False),
    sa.Column('scheduled_date', sa.Date(), nullable=True),
    sa.Column('completed_date', sa.Date(), nullable=True),
    sa.Column('mileage_at_service', sa.Integer(), nullable=True),
    sa.Column('next_service_mileage', sa.Integer(), nullable=True),
    sa.Column('next_service_date', sa.Date(), nullable=True),
    sa.Column('cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('service_provider', sa.String(length=300), nullable=True),
    sa.Column('performed_by', sa.String(length=300), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maintenance_records_scheduled_date'), 'maintenance_records', ['scheduled_date'], unique=False)
    op.create_index(op.f('ix_maintenance_records_vehicle_id'), 'maintenance_records', ['vehicle_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_maintenance_records_vehicle_id'), table_name='maintenance_records')
    op.drop_index(op.f('ix_maintenance_records_scheduled_date'), table_name='maintenance_records')
    op.drop_table('maintenance_records')
    op.drop_index(op.f('ix_expenses_vehicle_id'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_date'), table_name='expenses')
    op.drop_table('expenses')
    op.drop_index(op.f('ix_contracts_vehicle_id'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_end_date'), table_name='contracts')
    op.drop_table('contracts')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
