"""add_vehicle_driver_mileage_document

Revision ID: 7cddff1407cc
Revises: 2f316daf4431
Create Date: 2026-02-23 13:39:34.995296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cddff1407cc'
down_revision: Union[str, None] = '2f316daf4431'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('entity_type', sa.Enum('VEHICLE', 'DRIVER', 'MAINTENANCE', 'CONTRACT', 'EXPENSE', name='entity_type'), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('PHOTO', 'SCAN', 'INVOICE', 'ACT', 'CONTRACT', 'LICENSE', 'MEDICAL', 'INSURANCE', 'OTHER', name='document_type'), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('s3_key', sa.String(length=1000), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_entity_id'), 'documents', ['entity_id'], unique=False)
    op.create_table('drivers',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('employee_id', sa.String(length=50), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('license_number', sa.String(length=50), nullable=True),
    sa.Column('license_category', sa.String(length=20), nullable=True),
    sa.Column('license_expiry', sa.Date(), nullable=True),
    sa.Column('medical_expiry', sa.Date(), nullable=True),
    sa.Column('hire_date', sa.Date(), nullable=True),
    sa.Column('department', sa.String(length=200), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'ON_LEAVE', 'TERMINATED', name='driver_status'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id')
    )
    op.create_table('vehicles',
    sa.Column('license_plate', sa.String(length=20), nullable=False),
    sa.Column('vin', sa.String(length=17), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.Column('body_type', sa.Enum('SEDAN', 'SUV', 'TRUCK', 'VAN', 'BUS', 'MINIVAN', 'PICKUP', name='body_type'), nullable=False),
    sa.Column('fuel_type', sa.Enum('GASOLINE', 'DIESEL', 'GAS', 'ELECTRIC', 'HYBRID', name='fuel_type'), nullable=False),
    sa.Column('engine_volume', sa.Float(), nullable=True),
    sa.Column('transmission', sa.Enum('MANUAL', 'AUTOMATIC', 'CVT', 'ROBOT', name='transmission_type'), nullable=False),
    sa.Column('seats', sa.Integer(), nullable=True),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('purchase_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('current_mileage', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'IN_MAINTENANCE', 'DECOMMISSIONED', 'RESERVED', name='vehicle_status'), nullable=False),
    sa.Column('assigned_driver_id', sa.UUID(), nullable=True),
    sa.Column('department', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_driver_id'], ['drivers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicles_license_plate'), 'vehicles', ['license_plate'], unique=True)
    op.create_index(op.f('ix_vehicles_vin'), 'vehicles', ['vin'], unique=True)
    op.create_table('mileage_logs',
    sa.Column('vehicle_id', sa.UUID(), nullable=False),
    sa.Column('recorded_by', sa.UUID(), nullable=True),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('source', sa.Enum('MANUAL', 'OBD', 'GPS', name='mileage_source'), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mileage_logs_vehicle_id'), 'mileage_logs', ['vehicle_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mileage_logs_vehicle_id'), table_name='mileage_logs')
    op.drop_table('mileage_logs')
    op.drop_index(op.f('ix_vehicles_vin'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_license_plate'), table_name='vehicles')
    op.drop_table('vehicles')
    op.drop_table('drivers')
    op.drop_index(op.f('ix_documents_entity_id'), table_name='documents')
    op.drop_table('documents')
    # ### end Alembic commands ###
